name: CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: nuget/setup-nuget@v1

    - name: Pre-build
      run: nuget restore idk\IDK.sln
      
    - name: Build
      run: MSBuild.exe idk\IDK.sln -t:"50 Unit Testing" -p:Configuration="Debug" -p:Platform="x64"  

    - name: Test
      run: '& "idk\bin\50 Unit TestingD.exe"'
